# Generated by Django 6.0.6 on 2026-07-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], default='any', max_length=10)),
                ('preferred_experience', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'student preference',
                'verbose_name_plural': 'student preferences',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='grade level')),
                ('school', models.CharField(blank=True, max_length=200, null=True, verbose_name='school')),
                ('parent_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='parent/guardian name')),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='parent/guardian phone')),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='parent/guardian email')),
                ('learning_goals', models.TextField(blank=True, max_length=2000, null=True, verbose_name='learning goals')),
                ('preferred_mode', models.CharField(choices=[('home_tuition', 'Home Tuition'), ('online_tuition', 'Online Tuition'), ('both', 'Both')], default='both', max_length=20, verbose_name='preferred teaching mode')),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='maximum budget per hour')),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('total_hours_learned', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'student profile',
                'verbose_name_plural': 'student profiles',
            },
        ),
    ]
