# Generated by Django 6.0.6 on 2026-07-04 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day of week')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'availability',
                'verbose_name_plural': 'availabilities',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('issuing_organization', models.CharField(max_length=300, verbose_name='issuing organization')),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='credential ID')),
                ('credential_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='credential URL')),
                ('issue_date', models.DateField(verbose_name='issue date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('does_not_expire', models.BooleanField(default=False, verbose_name='does not expire')),
                ('file', models.FileField(blank=True, null=True, upload_to='teachers/certificates/', verbose_name='certificate file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('organization', models.CharField(max_length=300, verbose_name='organization')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='location')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('is_current', models.BooleanField(default=False, verbose_name='current position')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'experience',
                'verbose_name_plural': 'experiences',
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200, verbose_name='degree')),
                ('institution', models.CharField(max_length=300, verbose_name='institution')),
                ('field_of_study', models.CharField(max_length=200, verbose_name='field of study')),
                ('start_year', models.PositiveIntegerField(verbose_name='start year')),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='end year')),
                ('is_current', models.BooleanField(default=False, verbose_name='currently studying')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='teachers/qualifications/', verbose_name='certificate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'qualification',
                'verbose_name_plural': 'qualifications',
                'ordering': ['-end_year', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'specific availability',
                'verbose_name_plural': 'specific availabilities',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TeacherGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='teachers/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='caption')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'gallery image',
                'verbose_name_plural': 'gallery images',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='teachers_su_name_1b204f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('headline', models.CharField(blank=True, max_length=500, null=True, verbose_name='headline')),
                ('about', models.TextField(blank=True, max_length=5000, null=True, verbose_name='about')),
                ('teaching_mode', models.CharField(choices=[('home_tuition', 'Home Tuition'), ('online_tuition', 'Online Tuition'), ('both', 'Both')], default='both', max_length=20, verbose_name='teaching mode')),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('intermediate', 'Intermediate (2-5 years)'), ('experienced', 'Experienced (5-10 years)'), ('expert', 'Expert (10+ years)')], default='entry', max_length=20, verbose_name='experience level')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='years of experience')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='hourly rate')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('service_area', models.PositiveIntegerField(default=10, help_text='Maximum distance in km the teacher is willing to travel', verbose_name='service area (km)')),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='meeting link')),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='teachers/profiles/', verbose_name='profile image')),
                ('demo_video', models.FileField(blank=True, null=True, upload_to='teachers/demo_videos/', verbose_name='demo video')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='total students')),
                ('total_hours', models.PositiveIntegerField(default=0, verbose_name='total hours taught')),
                ('total_bookings', models.PositiveIntegerField(default=0, verbose_name='total bookings')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='average rating')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='total reviews')),
                ('completion_rate', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage of completed bookings', max_digits=5, verbose_name='completion rate')),
                ('response_time', models.PositiveIntegerField(default=24, help_text='Average response time in hours', verbose_name='response time (hours)')),
                ('website', models.URLField(blank=True, max_length=500, null=True, verbose_name='website')),
                ('linkedin', models.URLField(blank=True, max_length=500, null=True, verbose_name='linkedin')),
                ('youtube', models.URLField(blank=True, max_length=500, null=True, verbose_name='youtube')),
                ('is_available', models.BooleanField(default=True, verbose_name='available for booking')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('max_students', models.PositiveIntegerField(default=10, verbose_name='max students')),
                ('languages', models.ManyToManyField(blank=True, related_name='teachers', to='teachers.language')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='teachers.subject')),
            ],
            options={
                'verbose_name': 'teacher profile',
                'verbose_name_plural': 'teacher profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
