# Generated by Django 6.0.6 on 2026-07-04 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachergallery',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='teachers.teacherprofile'),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_availability', to='teachers.teacherprofile'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='teachers.teacherprofile'),
        ),
        migrations.AddField(
            model_name='experience',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='teachers.teacherprofile'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='teachers.teacherprofile'),
        ),
        migrations.AddField(
            model_name='availabilitycalendar',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='teachers.teacherprofile'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['user', 'is_verified'], name='teachers_te_user_id_5ddf17_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['hourly_rate'], name='teachers_te_hourly__e94d46_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['average_rating'], name='teachers_te_average_052e48_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['years_of_experience'], name='teachers_te_years_o_2722f0_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['teaching_mode'], name='teachers_te_teachin_001bab_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['is_available'], name='teachers_te_is_avai_d3d8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['location'], name='teachers_te_locatio_bb64c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacheravailability',
            unique_together={('teacher', 'date', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='availabilitycalendar',
            unique_together={('teacher', 'day_of_week', 'start_time')},
        ),
    ]
