# Generated by Django 6.0.6 on 2026-07-04 07:05

import apps.common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_id', models.CharField(default=apps.common.utils.generate_reference_id, editable=False, max_length=50, unique=True, verbose_name='booking ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled'), ('in_progress', 'In Progress')], default='pending', max_length=20, verbose_name='status')),
                ('teaching_mode', models.CharField(choices=[('home_tuition', 'Home Tuition'), ('online_tuition', 'Online Tuition')], max_length=20, verbose_name='teaching mode')),
                ('preferred_date', models.DateField(verbose_name='preferred date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='duration (hours)')),
                ('location', models.CharField(blank=True, help_text='Physical address for home tuition', max_length=500, null=True, verbose_name='location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meeting_link', models.URLField(blank=True, help_text='Online meeting link for online tuition', max_length=500, null=True, verbose_name='meeting link')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='hourly rate')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total amount')),
                ('is_paid', models.BooleanField(default=False, verbose_name='paid')),
                ('student_notes', models.TextField(blank=True, max_length=2000, null=True, verbose_name='student notes')),
                ('teacher_notes', models.TextField(blank=True, max_length=2000, null=True, verbose_name='teacher notes')),
                ('cancellation_reason', models.TextField(blank=True, max_length=1000, null=True, verbose_name='cancellation reason')),
                ('reschedule_count', models.PositiveIntegerField(default=0)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rescheduled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_date', models.DateField(verbose_name='new date')),
                ('new_start_time', models.TimeField(verbose_name='new start time')),
                ('new_end_time', models.TimeField(verbose_name='new end time')),
                ('reason', models.TextField(max_length=1000, verbose_name='reason')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'reschedule request',
                'verbose_name_plural': 'reschedule requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
