# Generated by Django 6.0.6 on 2026-07-04 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='teachers.teacherprofile'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['teacher', 'rating'], name='reviews_rev_teacher_4c7564_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('student', 'teacher')},
        ),
    ]
